(
("weblog.el" "<a href=\"{blogToplevel}weblog.el\">weblog.el</a>")
("billstclair.com" "<a href=\"http://billstclair.com/\">billstclair.com</a>")
("end the war on freedom" "<a href=\"http://billstclair.com/blog/\">End the War on Freedom</a>")
("blogmax.el" "<a href=\"{blogToplevel}blogmax.el\">blogmax.el</a>")
("blogmax.elc" "<a href=\"{blogToplevel}blogmax.elc\">blogmax.elc</a>")
("dave winer" "<a href=\"http://www.scripting.com/\">Dave Winer</a>")
("manila" "<a href=\"http://manila.userland.com/\">Manila</a>")
("editthispage.com" "<a href=\"http://www.editthispage.com\">EditThisPage.com</a>")
("gnugpl" "<a href=\"http://www.gnu.org/copyleft/gpl.html\">GNU General Public License</a>")
("blogmax.zip" "<a href=\"{blogToplevel}blogmax.zip\">blogmax.zip</a>")
("e-gold" "<a href=\"http://www.e-gold.com/\">e-gold</a>")
("paypal" "<a href=\"http://www.paypal.com/\">PayPal</a>")
("emacs" "<a href=\"http://www.gnu.org/software/emacs/\">Emacs</a>")
("weblog.ini" "<a href=\"{blogToplevel \"stories/\"}weblogini.html\">weblog.ini</a>")
("freshmeat" "<a href=\"http://freshmeat.net/\">freshmeat</a>")
("rsslink" "<a href=\"{blogToplevel}rss.xml\" title=\"This is a link to this site's RSS channel: {siteName}\">
<img src=\"xml.png\" alt=\"xml\" height=\"14\" width=\"36\" border=\"0\"></a>")
)
